[package]
name = "xtask"
version = "0.1.0"
authors = ["cally"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
m_pefile-rs = { path = "../../m_PEFile-rs" }
